### ISSUE TITLE
all factors found but unfactor.py does no output

### ISSUE THREAD

**Issue by darkskysofrenia** [Googulator/TeslaCrack#10]
i have finished tou factorise the publick key ( not the bitcoin key ) when i use unfactor.py it does no output ... i've test add print in python script to see if he goes in all loops , the print out but no error message or possible key . 
any idea ?

pbkey : 0BD5B4F3CB4D761648C9BD9AA4A03E570D14294E8499A5F9F05D7574278A1D5A79D5A19D1BEB34B196D0040B9E25EB253C9EB45FDAC4EFB6AFB9C10EEBFE8FD2

factors : 
http://factordb.com/index.php?query=619838370694573489677615657761314429981701046554484927594725478425232273862780267750658149602941057652096353317803469670070211348863163671132406890270674

**Comment by JonnyTech** [comment]
Try unfactor-ecdsa.py instead

**Comment by darkskysofrenia** [comment]
unfactor ecdsa works ....but with pbkey not bitcoin key ... any explication ? thanks again

**Comment by TamaBaka** [comment]
Make sure you enter in ALL factors, even if there are multiples of them.  If '2' appears 3 times, then you list it 3 times

**Comment by darkskysofrenia** [comment]
sure, 
python unfactor.py DSC_3480.JPG.vvv 2 3 11393 6149590188799 181869687108473013068158571977 3731778109277946991196464262550236276396701 2172535101762283539862062065407677298527831888425090574880088761 does no output but unfactor-ecdsa output one key , theses factors are from the public key

**Comment by Googulator** [comment]
Did you put '\xff\xd8' as the magic number?

**Comment by darkskysofrenia** [comment]
i din't modify your .py , unfactor-ecdsa.py give me one key i add it to teslacrack.py and it's uncrypt the file fine. I can send you all files if you want make some tests.

**Comment by Googulator** [comment]
That's a way around it, yes. Unfactor.py is designed to be edited before use, unless you're using a PDF as the sample file, as it already contains the right magic number for PDFs.

**Comment by ahsaad123** [comment]
Googulator, I can't thank you enough for sharing your wonderful work. It worked just fine for me but I noticed:
1- I got 3 repeated public keys. I added only once and it worked on my files.
2- I did not modify the magic keys of your py and it worked ok on pdf, jpg, doc, docx, and dwg.
perhaps you can comment on that.

**Comment by Googulator** [comment]
Repeated public keys are a known bug.

You only need to modify the file magic if you are not using a PDF file as the sample for unfactoring. Once you get the key, you don't need to fiddle around with the magic anymore.

**Comment by ahsaad123** [comment]
Its clear now. And again THANK you so much your work is great help.
