### ISSUE TITLE
Help desperately needed

### ISSUE THREAD

**Issue by MirkoHelp** [Googulator/TeslaCrack#12]
Hello and sorry for abruptly asking this, but I'm not a coder and, although not a newbie with computers and malware... well, I'm encountering some difficulties in running the TeslaCrack on an infected PC of a non-for-profit organization I'm trying to help.
Would it be possible to have some help?

Many many thanks

**Comment by MirkoHelp** [comment]
I tried to get in touch with email or private message, but no such feature is available...

**Comment by mariosangiorgio** [comment]
Where are you stuck?

**Comment by MirkoHelp** [comment]
Ahhhh... the steps were so complicated I cannot remember... It will take me time to sum up...
- I installed Python 2.7.11 64-bit (the infected machine is 64-bit capable);
- I made thethe PATH thing and also executed the commands in step 2;
- I placed msieve152 in a directory in C, including the factmsieve.py (which lies in the ggnfs directory);
- placed ggnfs in a directory on C;
- placed TeslaCrack in a directory on C;
- found a .pdf file with the .vvv extension and put it in the same directory as TeslaCrack;
- at this point I do as instructed by point 4: I open a cmd prompt, change to TeslaCrack directory and run python teslacrack.py;
- at this point I get the following:

Cannot decrypt ./nota contabile 01 2013.pdf.vvv, unknown key
Software has encountered the following unknown AES keys, please crack them first
 using msieve:
308ADB073A47BF6D9AE403A49783B85E1E56A0951F503311121A4BE9058B2DD784D2EBA16F454C51
BC38329C1B0584B9B7DC3544914B2489DE7E2EBD59AB03EC found in ./nota contabile 01 20
13.pdf.vvv
Alternatively, you can crack the following Bitcoin key(s) using msieve, and use
them with TeslaDecoder:
5B8EF3010D11AFD1D3B49E34295F79E33A6F4991E1BAE26E972DCAE181D6E855C4EE01B01EF1077E
36973487DE7CF8BCD33F9234011FCC3BB4D77FDE6B59257A found in ./nota contabile 01 20
13.pdf.vvv

Ah, by the way: thanks a lot for the support!

**Comment by MirkoHelp** [comment]
@mariosangiorgio : are you from Italy as me?

**Comment by captainmeto** [comment]
@MirkoHelp  thx for good topic, im watching

**Comment by joseluu** [comment]
Here are your factors as found with yafu:

fac: factoring
25423720211309947441889341140587217852195569024866870216658119871
04732946725580607769252426038346486334448145993914180151998635730174140363332468
163150828
fac: using pretesting plan: normal
fac: no tune info: using qs/gnfs crossover of 95 digits
div: primes less than 10000
fmt: 1000000 iterations
rho: x^2 + 3, starting 1000 iterations on C146
rho: x^2 + 2, starting 1000 iterations on C146
rho: x^2 + 2, starting 1000 iterations on C141
rho: x^2 + 2, starting 1000 iterations on C135
rho: x^2 + 1, starting 1000 iterations on C135
pm1: starting B1 = 150K, B2 = gmp-ecm default on C135
ecm: 30/30 curves on C125, B1=2K, B2=gmp-ecm default
ecm: 15/74 curves on C125, B1=11K, B2=gmp-ecm default
ecm: 5/58 curves on C108, B1=11K, B2=gmp-ecm default
ecm: 52/52 curves on C91, B1=11K, B2=gmp-ecm default
ecm: 5/214 curves on C91, B1=50K, B2=gmp-ecm default, ETA: 34 sec
Total factoring time = 4.8943 seconds

**_factors found**_

P1 = 2
P1 = 2
P2 = 11
P2 = 13
P2 = 41
P2 = 53
P2 = 73
P5 = 29483
P7 = 9035771
P10 = 5787150907
P17 = 63737733690194947
P18 = 186739694324527283
P23 = 13999153543524163152001
P69 = 109074630884173839378011527744188345704849478179842711197909123176131

ans = 1

Your next step is to run:

python unfactor.py your_file.pdf.vvv  2 2 11 13 41 53 73 29483 9035771
5787150907 63737733690194947 186739694324527283
13999153543524163152001
109074630884173839378011527744188345704849478179842711197909123176131

Read more at
http://www.malekal.com/how_recover-teslacrypt-extension-vvv/#7cT0SR4XUXxRXDhQ.99

**Comment by MirkoHelp** [comment]
WOW Godziluu, thanks a lot.
I will try the next step... but will need to do this for all docs affected... and there's hundreds...
I'll be at the affected PC tomorrow morning.
Again: thanks for now!

**Comment by mariosangiorgio** [comment]
@MirkoHelp, once you do this for a file it's going to be much easier to get all the other files back. They are all encrypted with the same key (or with a very limited number of them) so you won't need to do the full procedure for every file.

I recommend you to follow @Godziluu advice and run `unfactor.py`. If you're not sure how to proceed from there post here the output of that command and we can guide you through the change you need to make to `teslacrack.py` to add the key.

**Comment by MirkoHelp** [comment]
two silly questions (I feel really stupid and ignorant here):
1) I tried to copy paste the text above (editing the filename, obviously) into Python's command line, but get a syntax error...
2) I presume this is because of the carriage returns in the text above: should I remove those returns?

**Comment by mariosangiorgio** [comment]
Yes, you need to remove the carriage returns.
Here you can find more detail on how to execute the Python script http://pythoncentral.io/execute-python-script-file-shell/

**Comment by MirkoHelp** [comment]
I get a syntax error: invalid syntax...
I removed the carriage returns and also changed the file name (there were spaces in it and I put -)

**Comment by JonnyTech** [comment]
The following is one long line:

> python unfactor.py "nota contabile 01 2013.pdf.vvv" 2 2 11 13 41 53 73 29483 9035771 5787150907 63737733690194947 186739694324527283 13999153543524163152001 109074630884173839378011527744188345704849478179842711197909123176131

Copy and paste it to your command prompt.
Note that your filename is enclosed in quotes.

**Comment by MirkoHelp** [comment]
Hi all.
I understood what I got wrong: this time I opened the prompt, changed to teslacrack's directory and the pasted the line given by JonnyTech...
The PC is working and the cursor blinking, without a prompt...

**Comment by MirkoHelp** [comment]
I see the CPU workload is between 50 and 70%...
One more question: how long can I expect it to last?

By the way, I will never write it often enough: thanks to all for all your kind help, it is enormously appreciated!!!!

**Comment by JonnyTech** [comment]
Has it completed yet? It really should not take too long at all
For me it was about 10 minutes, but it depends on your system specs
I found that unfactor_ecdsa.py worked better than unfactor.py

**Comment by MirkoHelp** [comment]
Hi all.
After roughly 30 minutes I had to go and left the office.
I cannot go back until Monday morning... so... who knows how long it'll 
take...
Sys specs aren't that grand: if I remember this correctly it is a very average Dual Core.

**Comment by MirkoHelp** [comment]
It is a Pentium G3250, so it is a 2 core...
Anyway, it is Monday morning, 4 days have passed and... NOTHING!! The terminal window is closed and the PC was asking for login.
I put the PC into max performance, switched off all schemes for hibernation, suspension and so forth, but forgot to turn off the "go back to login screen" after screen off.
I think he simply finished crunching... but how can I know it?

**Comment by darkskysofrenia** [comment]
have a look to system and app log to see if your computer don't have automaticaly reboot cause of microsoft updates ....
click on start, run , "eventvwr"

**Comment by JonnyTech** [comment]
Please post your pdf.vvv file to a sharing host.

**Comment by MirkoHelp** [comment]
Checking remotely from home now... set up TeamViewer...
@JonnyTech :+1: 
I'll post a link to Dropbox here: is it ok? Or have you another service to suggest?

**Comment by MirkoHelp** [comment]
@darkskysofrenia Will check tomorrow morning... now that I think of it, it is possible the bloody MS updates are set to auto...

**Comment by JonnyTech** [comment]
Yep, anywhere you like, I'll grab it and see what I can do..

**Comment by MirkoHelp** [comment]
@JonnyTech 
Hi there and thanks for the help. Couldn't do it before...
Will you crunch the data for me?

**Comment by MirkoHelp** [comment]
Here's the file I tried to unfactor:
https://www.dropbox.com/s/hoffesq277w695q/nota-contabile-01-2013.pdf.vvv?dl=0
Just to be sure, here's another affected file:
https://www.dropbox.com/s/rhhp4loti6r5q7w/Pulizia%20annuale.docx.vvv?dl=0

THANKS A LOT!!!

**Comment by JonnyTech** [comment]
Result on pdf file:

> Found AES private key: b'\x35\xe2\x93\x95\xd5\x05\xec\x1c\xd5\x9d\x4c\xf7\xe7\x85\xb0\xea\xb6\x7c\x69\x1c\x8a\xac\x80\x4e\x80\xec\x66\x72\xe9\x02\x9a\xdb' (35E29395D505EC1CD59D4CF7E785B0EAB67C691C8AAC804E80EC6672E9029ADB)

**Comment by JonnyTech** [comment]
Edit your teslacrack.py file to match this section:

> # Add your key(s) here.
> known_keys = {
>     b'D4E0010A8EDA7AAAE8462FFE9562B29871B9DA186D98B5B15EC9F77803B60EAB12ADDF78CBD4D9314A0C31270CC8822DCC071D10193D1E612360B26582DAF124': b'\xEA\x68\x5A\x3C\xDB\x78\x0D\xF2\x12\xEB\xAA\x50\x03\xAD\xC3\xE1\x04\x06\x3E\xBC\x25\x93\x52\xC5\x09\x88\xB7\x56\x1A\xD1\x34\xA5',
>     b'9F2874FB536C0A6EF7B296416A262A8A722A38C82EBD637DB3B11232AE0102153C18837EFB4558E9E2DBFC1BB4BE799AE624ED717A234AFC5E2F8E2668C76B6C': b'\xCD\x0D\x0D\x54\xC4\xFD\xB7\x64\x7C\x4D\xB0\x95\x6A\x30\x46\xC3\x4E\x38\x5B\x51\xD7\x35\xD1\x7C\x00\x9D\x47\x3E\x02\x84\x27\x95',
>     b'115DF08B0956AEDF0293EBA00CCD6793344D6590D234FE0DF2E679B7159E8DB05F960455F17CDDCE094420182484E73D4041C39531B5B8E753E562910561DE52': b'\x1A\xDC\x91\x33\x3E\x8F\x6B\x59\xBB\xCF\xB3\x34\x51\xD8\xA3\xA9\x4D\x14\xB3\x84\x15\xFA\x33\xC0\xF7\xFB\x69\x59\x20\xD3\x61\x8F',
>     b'308ADB073A47BF6D9AE403A49783B85E1E56A0951F503311121A4BE9058B2DD784D2EBA16F454C51BC38329C1B0584B9B7DC3544914B2489DE7E2EBD59AB03EC': b'\x35\xe2\x93\x95\xd5\x05\xec\x1c\xd5\x9d\x4c\xf7\xe7\x85\xb0\xea\xb6\x7c\x69\x1c\x8a\xac\x80\x4e\x80\xec\x66\x72\xe9\x02\x9a\xdb',
> }

Good luck!

**Comment by MirkoHelp** [comment]
WOW!
Apparently it is solved! I have new files which match old files. All new files have the correct extension, old affected files have the .vvv extension.
Will delete all vvv files once matching files are viewable again.
Checking them one by one.
Had a few "cannot open" messages in the command prompt during decrypting...

**Comment by JonnyTech** [comment]
Good news! The files were successfully decrypted because you have new files without the .vvv extension otherwise an error message would have been displayed.

I don't know about the "cannot open" message. Are you able to view them with something like notepad? Maybe your system has locked them due to another reason. Try in safe mode or copy them to another computer and run teslacrack there.

**Comment by ahsaad123** [comment]
I had the (cannot open ) message and it was due to bad (stage language fonts) in the path of the file directory. Try to move the files to a simple location say C:\temp . Thus worked for me.

**Comment by MirkoHelp** [comment]
I recovered all the files inside the docs folder, and this is enough, I think.
Maybe I'll try Monday to launch a search for files with vvv extension, just to be sure nothing escaped.
Should this be the case I will relaunch TeslaCrack in safe mode and see what happens.
In the meantime I DEEPLY THANK ALL OF YOU: YOUR FREE HELP HAS BEEN INVALUABLE!!!

**Comment by Googulator** [comment]
Looks like this is solved.

**Comment by MirkoHelp** [comment]
Oh yes, sorry!
And thank you very much again.

Mirko

**Comment by raduville** [comment]
hello. I was trying to find my AES Key... but i failed many times. I don't know why. 
I've installed python, with ecdsa and bitcoin, i've downloaded teslacrack and other stuff... but i can't really find my key. Can anyone help me please? I've attached in here a file, it's a .doc file with the extension .ccc after i got that stupid virus. 

thanks a lot! 
[proiect.ccc.pdf](https://github.com/Googulator/TeslaCrack/files/420470/proiect.ccc.pdf)

PS: remove .pdf

**Comment by Demonslay335** [comment]
@raduville 

Use this key with BloodDolly's TeslaDecoder.

59824CFAAF4E50EDAD56F43F799D31BE92BD0C2C3F59726D385BE22EEE445F4C

http://www.bleepingcomputer.com/forums/t/576600/tesladecoder-released-to-decrypt-exx-ezz-ecc-files-encrypted-by-teslacrypt/

**Comment by raduville** [comment]
thank you so so so so much!!!!! I finally got my files back! 
You made my day, Sir!  God bless you!

**Comment by raduville** [comment]
anyway, could you explain me how did you found that key? Short steps.. but clear enough :D 
Thanks again!

**Comment by JonnyTech** [comment]
http://www.bleepingcomputer.com/news/security/teslacrypt-shuts-down-and-releases-master-decryption-key/

**Comment by Demonslay335** [comment]
@raduville 

TesalaDecoder includes the full steps on how to factor your key. It's just a matter of getting your SharedSecret1*PrivateKeyBC using TeslaViewer, factoring it to the respective primes using yafu, then refactoring the PrivateKeyBC using TeslaRefactor. Yours was a rather easy one that factored down to a C91 with ECM, then just took a few minutes for my i5 sieve the last factors.

It can take a bit to get setup if you've never done the factoring before, but I've been helping do this since December 2015, so it's muscle memory for me. ;)

**Comment by Demonslay335** [comment]
@JonnyTech 

The master key **only** works for **TeslaCrypt v3.0 / v4.0**. It does not work for previous versions (.ccc was v2.2.0).

**Comment by JonnyTech** [comment]
@Demonslay335 Indeed, my bad
