### ISSUE TITLE
Issue with pycrptodome install

### ISSUE THREAD

**Issue by juanpark** [Googulator/TeslaCrack#15]
Hi Googulator! As always I want to first express my gratitude for your work :-)

I have a blog post up for Korean users trying to decrypt TeslaCrypt 2.2 and earlier encrypted files.
One of the visitors mentioned that he is running a Windows 10 64 bit machine and ran into the following error after running pip install pycrptodome:

Collecting pycrptodome
Could not find a version that satisfies the requirement pycrptodome (from versions: )
No matching distribution found for pycrptodome

Any idea how this can be solved? Thanks!

**Comment by Googulator** [comment]
Missing second "y". The package name is "pycryptodome".

**Comment by juanpark** [comment]
Darn! That was stupid of me :-( Thanks!
