### ISSUE TITLE
ImportError: No module named 'services'

### ISSUE THREAD

**Issue by ekv88** [Googulator/TeslaCrack#18]
Traceback (most recent call last):
  File "C:\Python34\Project\TeslaC\unfactor_bitcoin.py", line 22, in <module>
    from pybitcoin.keypair import BitcoinKeypair
  File "C:\Python34\lib\site-packages\pybitcoin__init__.py", line 10, in <modul
e>
    import services
ImportError: No module named 'services'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Project\TeslaC\unfactor_bitcoin.py", line 24, in <module>
    from coinkit.keypair import BitcoinKeypair
  File "C:\Python34\lib\site-packages\coinkit__init__.py", line 12, in <module>

import services
ImportError: No module named 'services'

1st i had problem with "coinkit" but that was easy to fix, what do i need now?

**Comment by JonnyTech** [comment]
AFAIK TeslaCrack requires python version 2.7 and is currently incompatible with python 3.4

**Comment by Googulator** [comment]
Yes, we rely on pybitcoin (previously known as coinkit), which is not usable under 3.x

**Comment by ekv88** [comment]
Okey, thanks.
One more quick question, do i really need BTC address, or I can put dummy address?

**Comment by Googulator** [comment]
If you use unfactor_bitcoin.py, then you need to know the BTC address used by TeslaCrypt (can be found in the recovery file). The other unfactor scripts don't require it, they instead use the public key from the sample file.

**Comment by ekv88** [comment]
Yeah, I did find it in "NTUSER.DAT" :)
Thanks for everything bro! Managed to do it with TeslaDecoder 0.80 and "Set Key"
