### ISSUE TITLE
Not sure if script has frozen?

### ISSUE THREAD

**Issue by ryaniam** [Googulator/TeslaCrack#22]
Hi all,

I'm currently factoring using msieve and im not sure if it is still running or has frozen ( http://pastebin.com/wynteJhL ) - I checked factor db and it shows my factors but the last one seems way too long? Do I need to factor this one separately?

It's been 'running' for 5 days now. (Dell Latitude E7240, Core i5)

**Comment by Demonslay335** [comment]
It should be finishing there, it is working on the matrices.

I'll have your factors posted to factordb.com in a few minutes, yafu is tearing through it like butter.

**Comment by Demonslay335** [comment]
When you are factoring, msieve and yafu will automatically start working on the next largest cofactor when it pulls a prime out of it, so no worries about going to factor a different number really.

Here's your factors.

http://www.factordb.com/index.php?id=1100000000817170831

**Comment by ryaniam** [comment]
Thankyou so much! running unfactor.py now :D

**Comment by Googulator** [comment]
Looks like you were using the buggy SVN 939 build. 939 and 942 are buggy, they tend to crash or freeze in the matrix crunching step. I've posted on MersenneForums to get the factoring binaries page updated, as way too many people are falling victim to these broken builds of msieve - and even those who use YAFU instead will likely end up with the outdated ggnfs-lasieve binaries located there, which are very inefficient and slow compared to later versions found on mersenneforums.org.

**Comment by Demonslay335** [comment]
@Googulator Ahh, that explains a lot with users reporting crashes. I never had the buggy version, I've got msieve SVN 946.

**Comment by ryaniam** [comment]
Was taking too long with unfactor.py on the core i5. now running unfactor.py on an 8 core azure VM. What's the normal ETA for it to find the AES key?

**Comment by Demonslay335** [comment]
@ryaniam Double-check how you are using unfactor.py. It should literally take seconds when given the correct arguments. If you had factorized the "Bitcoin" key, you will need to use unfactor_ecdsa.py instead.

**Comment by ryaniam** [comment]
Definitely using unfactor.py -  This is the command I have fed it:

unfactor.py test.vvv 2 3 47 59 83 113 5273 14401 106996199 5971823755879 466941273191171 16226944585433923829 23391386973606340792798849390939319413583 115882702766689540064519361869671460452153

Have i correctly represented the first 2 factors in the command? They show as 2^5 and 3^2 on factor DB

**Comment by Demonslay335** [comment]
When it has powers, that means the factor is duplicated that many times. You have to input all of them.

```
unfactor.py test.vvv 2 2 2 2 2 3 3 47 59 83 113 5273 14401 106996199 5971823755879 466941273191171 16226944585433923829 23391386973606340792798849390939319413583 115882702766689540064519361869671460452153
```

**Comment by ryaniam** [comment]
Thanks! Trying that now.

**Comment by ryaniam** [comment]
Still going.. Not sure what I am doing wrong. I have attached my .vvv PDF to this thread in case anyone wants to run unfactor.py on it to see if it will work for others?
[test.zip](https://github.com/Googulator/TeslaCrack/files/105880/test.zip)

**Comment by ryaniam** [comment]
Found it with _ecdsa :)

**Comment by ankostis** [comment]
I think it works if you list each factor once; at least it worked like that
in my case.

**Comment by ryaniam** [comment]
ok now have more keys to work with. Is there anywhere i can find a binary for msieve that isn't known have issues?
