### ISSUE TITLE
New version of teslacrypt?  All files end with *.micro instead off *.vvv

### ISSUE THREAD

**Issue by Waldpiek** [Googulator/TeslaCrack#23]
Hello,

First of all THANKS for your vvv decrypter. It allready saved a few hundred baby pictures....

Got a call this morning from one of our customers. The got an email wit a ZIP file attached and they just clicked on it :-(

All userfiles are ending on *.micro (instead off *.vvv) but it looks very much the same.

Changed teslacrack.py to  search for *.micro but got a strange AES key....

There a two strange files in the documents folder, recover_file_eohjfoxxy.txt and recover_file_qatgbgqya.txt, all they contain are numbers.

I have taken the freedom to attach two  screenshots of (part) the documents folder, can upload all files shown if anybody is interested :-)

Thank U for reading, greetings from the Netherlands.

Frans
![screendump](https://cloud.githubusercontent.com/assets/16465679/12578921/2017be12-c424-11e5-8634-3b9aeb73c0a1.png)
![screendump2](https://cloud.githubusercontent.com/assets/16465679/12578920/201503f2-c424-11e5-8c8c-ee0bb570de6d.png)

**Comment by darkskysofrenia** [comment]
hello .micro is encrypted by a new variant of teslacrypt ( 3.0 ) like .xxx or .ttt no one is able to extract key from theses files for now but somme pepole are working on it , keep hope and wait

**Comment by rodrigous13** [comment]
Hello , thank you for your decryption at the vvv , taking advantage like to know if there is already a method for version .micro am suffering from this infection but do not see exits to resolution.
if by chance you have some method could tell me?

**Comment by Waldpiek** [comment]
Okay...... going to backup  the encrypted files and start all over :-)

Will be waiting to see whenever / if ever there comes a better day...

Thanks!!

**Comment by Googulator** [comment]
Closing this since TeslaCrypt 3.0 is a fundamentally different cryptor, with an algorithm actually copied from CTB Locker. If I manage to break it, that break will be a different program altogether.

**Comment by Demonslay335** [comment]
@Waldpiek @rodrigous13 

Just wanted to make sure you got the news that all versions of TeslaCrypt are now decryptable. :)

http://www.bleepingcomputer.com/news/security/teslacrypt-shuts-down-and-releases-master-decryption-key/
