### ISSUE TITLE
File Extension .encrypted

### ISSUE THREAD

**Issue by msalvini** [Googulator/TeslaCrack#27]
Hi, someone has already dealt with this cryptolocker ?
It created the file extension
es .gamma01.xla.encrypted
Thank you

**Comment by darkskysofrenia** [comment]
http://www.bleepingcomputer.com/forums/t/544555/zerolocker-a-new-destructive-encrypting-ransomware/

**Comment by msalvini** [comment]
Ok but I did not understand if there is solution , I do not need a antivirua but a procedure as we did for ramsowere extension .vvv !!

**Comment by Demonslay335** [comment]
@msalvini According to the article @darkskysofrenia linked, there is a brute-force tool available for ZeroLocker, assuming that is the actual ransomware you are dealing with.

[Vinsula releases free tool to brute force ZeroLocker decryption keys](http://www.bleepingcomputer.com/forums/t/554915/vinsula-releases-free-tool-to-brute-force-zerolocker-decryption-keys/)

It looks like [CoinLocker](http://www.bleepingcomputer.com/forums/t/565557/coin-locker-a-ransomware-that-tips-its-hat-to-julius-caesar/?hl=%2Bcoinlocker) uses the .encrypted extension, whereas ZeroLocker uses .encrypt. Compare the ransom note shown in both topics to determine which one you were hit with specifically. Both topics discuss how to recover from the respective ransomware.

**Comment by msalvini** [comment]
k I 'm doing a brute force utility to file with hopefully give me the key .
my case has an extension
.encrypted and not .encrypt so I should orient more about
CoinLocker ! However now I end up with brute force UnlockZeroLocker.exe then we see the results .
 thank you

**Comment by Demonslay335** [comment]
Can you post the ransom note you have? It seems these two variants will clearly state their name in the ransom note, so it should be easy to tell.

If UnlockZeroLocker and CoinLocker Decrypter don't work for you, we'll need to get more information to determine what exact ransomware you are against (always a possibility of something new).

**Comment by msalvini** [comment]
# 

```
    !!! ABBIAMO CRIPTATO VOSTRI FILE CON IL VIRUS Crypt0L0cker !!!
```

# 

I vostri file importanti (compresi quelli sui dischi di rete, USB, ecc): foto,
video, documenti, ecc sono stati criptati con il nostro virus Crypt0L0cker.
L'unico modo per ripristinare i file è quello di pagare noi. In caso contrario,
i file verranno persi.

Utilizzare questo link per pagare per i file di recupero:
http://javajvlsworf3574.torfilter.ch/yom0kf.php?user_code=tbl5vi&user_pass=1943

---

---

[=]  Che cosa è successo ai miei file?

  I vostri file importanti: foto, video, documenti, ecc sono stati
  crittografati con il nostro virus Crypt0L0cker. Questo virus utilizza molto
  forte algoritmo di crittografia - RSA-2048. Rottura di algoritmo di
  crittografia RSA-2048 è impossibile senza la speciale chiave di
  decrittazione.

[=] Come faccio a ripristinare i miei file?

  I file sono ora inutilizzabili e illeggibile, è possibile verificare che
  cercando di aprirli. L'unico modo per ripristinare la loro è quello di
  utilizzare il nostro software di decodifica. è possibile acquistare questo
  software di decodifica sul nostro
  sito web (http://javajvlsworf3574.torfilter.ch/yom0kf.php?user_code=tbl5vi&user_pass=1943).

[=] Cosa devo fare dopo?

  Si consiglia di visitare il
  nostro sito (http://javajvlsworf3574.torfilter.ch/yom0kf.php?user_code=tbl5vi&user_pass=1943)
  e acquistare decrittografia per il tuo PC.

[=] Non riesco ad accedere al tuo sito web, cosa devo fare?

  Il nostro sito web dovrebbe essere accessibile da uno di questi link::
  http://javajvlsworf3574.torfilter.ch/yom0kf.php?user_code=tbl5vi&user_pass=1943
http://javajvlsworf3574.torconnection.ch/yom0kf.php?user_code=tbl5vi&user_pass=1943
http://javajvlsworf3574.toragent.ch/yom0kf.php?user_code=tbl5vi&user_pass=1943
http://javajvlsworf3574.onion.link/yom0kf.php?user_code=tbl5vi&user_pass=1943

  http://javajvlsworf3574.onion/yom0kf.php?user_code=tbl5vi&user_pass=1943 (utilizzando il browser TOR)

  Se per qualsiasi motivo questi indirizzi non sono disponibili, si prega di
  seguire le istruzioni:
    1. Scaricare e installare TOR browser:
       http://www.torproject.org/projects/torbrowser.html.en
    2. Al termine dell'installazione, eseguire il browser e attendere
       l'inizializzazione.
    3. Digitare nella barra degli indirizzi:
       http://javajvlsworf3574.onion/yom0kf.php?user_code=tbl5vi&user_pass=1943
    4. L'accesso al nostro sito.

  Inoltre è possibile contattarci via e-mail: decrypthelp@mail333.com

---

---

Credenziali di Accesso:
  URL:       http://javajvlsworf3574.torfilter.ch/yom0kf.php
  User-Code: tbl5vi
  User-Pass: 1943

**Comment by Demonslay335** [comment]
Looks like it is claiming to be [Crypt0L0cker](http://www.bleepingcomputer.com/forums/t/574686/torrentlocker-changes-its-name-to-crypt0l0cker-and-bypasses-us-computers/), which is a variant of TorrentLocker. It also uses the .encrypted extension on files.

According to the [Crypt0L0cker Support Topic](http://www.bleepingcomputer.com/forums/t/574608/crypt0l0cker-support-topic), there is still no development on a solution. Your only option is to restore from backups. You may read the links I provided for more information.

**Comment by msalvini** [comment]
Hi guys , did not leave this cryptocker with .encrypted extension I almost preferred .vvv ! :)

**Comment by msalvini** [comment]
Excuse my INFECTED an information system cryptolocker .encrypted took the 02/02/2016 , it is a windows xp professional service pack 3 , I'm not the systema restore but I can do it manually recovering the 5 elements from the console .
Brought the system back to a full week of my files will be back to read or they will remain encrypted anyway?
Thank you
max

**Comment by Demonslay335** [comment]
If you are just using System Restore, it does nothing with files, only system settings and programs basically. You can follow the guide in the links above to attempt using recovery tools such as ShadowExplorer, Recuva, and PhotoRec. Mileage may vary, but they are your only chances if backups are not an option.

**Comment by msalvini** [comment]
Sorry Guys, I have been away there is news for the recovery of such RID1.RTF.encrypted file.
Thank you
max
