### ISSUE TITLE
Magic numbers to 0s

### ISSUE THREAD

**Issue by artoes** [Googulator/TeslaCrack#3]
Got a system affected byTeslaScript, but vvv files don't have magic numbers but 0s instead on the 4 first bytes ( and seems to be encrypted). Does teslacrack.py works the same even without magic numbers? I tried to remove the magic number check on line 40 and started factorization
Attached an example of such a file (removed vvv extension for github)
Anyway good job with this script

[Welcome to ASUS WebStorage.pdf](https://github.com/Googulator/TeslaCrack/files/67901/Welcome.to.ASUS.WebStorage.pdf)

**Comment by Bleeping** [comment]
Yes, it will still work. Edit teslacrack.py and change the magic to:

magic = b'\x00\x00\x00\x00'

**Comment by Googulator** [comment]
Seems like a new variant then. Does TeslaCrack's decryption method still work with it?

**Comment by fedeq4** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11921204/b72b8006-a762-11e5-9bc3-8d8b9b89347d.jpg)
hey googulator, im trying your tool with no luck.. just as artoes, my file didnt have magic number.. only 0s, tried what bleeping said and "it worked" but tesla crack opens and closes instant.. (sorry, my english is crap...) i've made a prnt scrn just to see something and it says the folowing: cannot decrypt (file name.vvv, in this case a jpg), unknown key.
softare has encountered the following unknown AES keys, please crack them first using msieve: and the "key"??

alternatively, you can crack the following bitcoin key(s) using msieve, and use them with tesladecoder: again some sort of "key"...

What can I do? can you give me a hand? like all the people that this fuckers fucks, ive lost practicaly all my life.... :( 
Maybe we can talk on another place more fluid?? thanks in advance man..

**Comment by TamaBaka** [comment]
You're not done yet.  You've only found the public key.

Go to step 5.  Use MSieve or YAFU to factorize that large hex number into a bunch of primes.

**Comment by fedeq4** [comment]
but is normal that it says unknown key?

im tech savvy but not that much... 
i've already downloaded yafu but I dont know how to factoryze the hex into primes? how i merge both things?? 
On a side note, teslacrack doesnt "print" the hex on any place.. it just opens and closes very fast. I have to put it manually on yafu? dont know how to use msieve, im not into programming or phyton at all.. Im bearly into edit xml or jbeam files on some of my games. 
sorry for being a noob..

**Comment by TamaBaka** [comment]
Yes. 

And instead of double-clicking teslacrack.py to run it, use the command prompt to navigate to the teslacrack.py file and run it with "python teslacrack.py"

Anyway, your screenshot already has the Hex key printed.  Feel free to manually enter it in.  (9AB18775...)

It would be easier if you pipe it to output.txt though.  Then you can open output.txt, which you'll find in the same directory, and copy that long sequence of characters directly.  "python teslacrack.py > output.txt"

**Comment by fedeq4** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11921529/4c630ecc-a769-11e5-82ab-b92f691d6db8.jpg)

entered manualy.. says ans=0 so im doing something wrong... 

thanks for the patiance tamabaka

**Comment by TamaBaka** [comment]
What else does it say?

**Comment by fedeq4** [comment]
nothing.. just ans=0 

im using yafu 1.34 x64 does it matters? 
![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11921611/027797c2-a76b-11e5-884b-d482136bd86b.jpg)

**Comment by TamaBaka** [comment]
I see.  I didn't use yafu, but I'm pretty certain that's not how you get yafu to factorize.  Type "help" or something to get a list of commands.  And paste down that hex string here so that it can be copied and pasted.

**Comment by fedeq4** [comment]
heres the hex: 9AB187758A71417382CD7A5717B9C99D42091C2B6FD9F68FDFC1266B75458142B6EB3E331145B7F4C3C712500F8125EBF290981EE2E88CA009B1588D22B2CA69

and what do i look for in the help department?
![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11921751/e765558a-a76c-11e5-9900-66d8981d393a.jpg)
![sin titulo2](https://cloud.githubusercontent.com/assets/16376212/11921752/e76a33ac-a76c-11e5-9f5b-157c172a6e48.jpg)
![sin titulo3](https://cloud.githubusercontent.com/assets/16376212/11921753/e7702974-a76c-11e5-81a7-3cf0c112b052.jpg)
![sin titulo4](https://cloud.githubusercontent.com/assets/16376212/11921754/e7764aac-a76c-11e5-8d94-f3cd1a03445d.jpg)

**Comment by TamaBaka** [comment]
According to the docs, I think your command would look something like: yafu "factor(9AB187758A71417382CD7A5717B9C99D42091C2B6FD9F68FDFC1266B75458142B6EB3E331145B7F4C3C712500F8125EBF290981EE2E88CA009B1588D22B2CA69)"

**Comment by fedeq4** [comment]
Still no luck.. but closer i think, you dont know how much i appreciate your help

![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11921891/079b5f82-a76f-11e5-9a3f-edc29823020e.jpg)

**Comment by TamaBaka** [comment]
Why not use msieve?

You can use this command immediately: 
msieve -v -e 0x9AB187758A71417382CD7A5717B9C99D42091C2B6FD9F68FDFC1266B75458142B6EB3E331145B7F4C3C712500F8125EBF290981EE2E88CA009B1588D22B2CA69

**Comment by fedeq4** [comment]
ive downloaded msieve152 but it says that its missing phtreadGC2.dll, ive downloaded the dll and put it in the folder of msieve, but it says 
![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11922018/1c21c0f2-a771-11e5-8a1a-4df019c06adf.jpg)

**Comment by fedeq4** [comment]
I've created a worktodo.ini with the command that you give me, now it says: sieving in progress (press ctrl c to pause) is it doing anything? cpu temp is that of idle, and no hdd light..

**Comment by TamaBaka** [comment]
Oh, that problem.  I got msieve somewhere else afterwards. 

http://gilchrist.ca/jeff/factoring/

The version that I use is the CUDA version, but it doesn't show the factorizations.  I use this one 1.52dev SVN 883 (with MPIR 2.6.0/GMP-ECM 6.4.4) to take the data leftover from the CUDA and obtain the factors.

And I don't know.  You might need to add some sort of verbose flag.

**Comment by fedeq4** [comment]
mmm I have a gtx 560ti with a fx6300.. dont know wich one can use

cpu is idling, so i belive that is not doing anything apart from saying sieving in progress etc..

*edit, it just displayed this:

![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11922193/7432f5d4-a773-11e5-90fa-6cab111f1b8e.jpg)

**Comment by TamaBaka** [comment]
Perfect, let it run for a few hours.

**Comment by fedeq4** [comment]
YESS! I thougt that it wasnt doing anything... but it just changed from 11 to 38 relations...

so i just leave it running and then what? it will return the primes and i just follow up from step 6?
Can i go to sleep and dont worry about loosing progress? (does it generate a log or something?)
do you know how much does it takes from the data that is shown? hope that it doesn't take too much, it worries me that there is some power fail or something like that.. is also just using 1 core of my cpu.
Ive been stressed like hell with this.. if I can retrieve the data lesson learn, BACKUP allways..

You rock TamaBaka! i wish that all goes well and finally can retrieve the most important things.. games and music actually don't matter.. but all of the pics from my little daughter, and work docs are compromised.. I even thought about paying up, but 500usd in my country is like 4 month salary... and this people dont deserve a cent..

![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11922586/ff4eae58-a776-11e5-8b90-21b7125081dd.jpg)

**Comment by joseluu** [comment]
Where did you find the cuda drivers ?
In my case I do not notice any acceleration using cuda, I suppose I am
missing them.
Thanks

**Comment by TamaBaka** [comment]
Yeah, there's may be significant overhead when using CUDA since you're taking a multihundred bit integer and using 64 bit operations on it.

src: https://devtalk.nvidia.com/default/topic/387075/integer-factorization-on-the-gpu-factoring-large-integers/

But it might help, maybe.

As for the drivers, I don't know if you need them.  I mean, I was using hashcat CUDA (oclHashcat) before this and I don't recall needing anything except updated drivers.

**Comment by martinaovivo** [comment]
In here
Four days running

141645 relations (54355 full + 87290 combined from 3237088 partial), need 306290

MSIEVE 1.52dev SVN 942

Waiting finish ...

I5 4430
GTX 760SC

**Comment by TamaBaka** [comment]
@fedeq4 

I ran the factorization for your key with MSieve.  Here are the factors that I found:

p1 factor: 5
p2 factor: 11
p2 factor: 19
p2 factor: 23
p2 factor: 29
p2 factor: 47
p4 factor: 1181
p4 factor: 3457
p6 factor: 352483
p10 factor: 1619691517
prp26 factor: 74143191606114801079972109
prp39 factor: 231419295217707765832329200835295551851
prp61 factor: 6183853869962559015040993794542699128471266939221704979810413

Go to step 6.

python unfactor.py 5 11 19 23 29 47 1181 3457 352483 1619691517 74143191606114801079972109 231419295217707765832329200835295551851 6183853869962559015040993794542699128471266939221704979810413

**Comment by fedeq4** [comment]
genious TamaBaka, you did it incredibly fast... my pc is still on 428 relations..

but it trows me this:
![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11928600/88826a66-a7b3-11e5-9b06-4d9f825a6dd7.jpg)

**Comment by TamaBaka** [comment]
I misread the documentation.

python unfactor.py sample.vvv 5 11 19 23 29 47 1181 3457 352483 1619691517 74143191606114801079972109 231419295217707765832329200835295551851 6183853869962559015040993794542699128471266939221704979810413

**Comment by artoes** [comment]
Hello,
Thanks for the answers. I tried to get the public key for different files with 0 magic number and it is consistent.
I started the factoring and I'm about 7% in 20hours. (300k relations needed)

TamaBaka, How did you do to factor it in such a short time ? Are you using a particular configuration / sieve script?

**Comment by fedeq4** [comment]
still i can't... tried sample.vvv, and the name of the file from wich i extracted the key.. im missing something
![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11928789/037d11fc-a7b5-11e5-8843-faa747d2ba27.jpg)

**Comment by TamaBaka** [comment]
@fedeq4
use "mb cpu.jpg.vvv".  You need to enclose it in double quotes because of that space in the middle.

@artoes 
I only had to find 93,000 relations.  And it gets faster the farther up the loop you go.  But the time gets exponentially longer the more relations you need to find.  When I had 40k relations to find, it took less than an hour.  93,000 relations took me 5 hours.

**Comment by fedeq4** [comment]
nono, is the same file @TamaBaka.. is called mb cpu.jpg, tried cpu.jpg.vvv but no go..

**Comment by TamaBaka** [comment]
Yeah, I edited my answer.  Otherwise, rename the sample file to something without spaces.  The python error is telling you that it can't find the file.

**Comment by fedeq4** [comment]
no spaces still the same.. error 2 no such file or directory

**Comment by TamaBaka** [comment]
Rename the file mb cpu.jpg.vvv to mb_cpu.jpg.vvv.  Then "python unfactor.py mb_cpu.jpg.vvv ..."

**Comment by fedeq4** [comment]
now it says that the file  doesn't appear to be teslacrypted?
![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11929245/20ee41ea-a7b8-11e5-8f56-1802424d31a0.jpg)

**Comment by fedeq4** [comment]
i've also tried with another file (with simple name, no spaces) to see if it changed something to edit the name.. same thing, "file doesn't appear to be teslacrypted"

**Comment by TamaBaka** [comment]
...umm, open up unfactor.py in wordpad and replace 
        **if not header.startswith('\xde\xad\xbe\xef\x04'):**

with 
        **if not header.startswith('\xde\xad\xbe\xef'):**

This is the difference between the string from teslacrack.py and unfactor.py where teslacrack.py uses the second string.  Save it and try running the python script again.

**Note: Please pay attention to the indents.  Whatever you start with is what you should end with.  The line to replace has 2x tabs or 8x spaces.  If it's hard to tell, align the indent with the previous line: header = f.read(414)**

Note 2: Remember to change your magic from **'%PDF'** to **'\xff\xd8'** because it's a JPEG

**Comment by fedeq4** [comment]
yes, i've already changed magic from '%PDF' to '\xff\xd8' .. just now replaced 
"if not header.startswith('\xde\xad\xbe\xef\x04'):

with 
if not header.startswith('\xde\xad\xbe\xef'):"

but still the same.. 
![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11929490/3968dd46-a7ba-11e5-9878-53ab892f47a9.jpg)

**Comment by TamaBaka** [comment]
Try running teslacrack.py on mb_cpu.jpg.vvv again.  If something is wrong, it will also tell you that the file doesn't appear to be teslacrypted.

It should just print out the public key again though.

**Comment by fedeq4** [comment]
yes it prints the key again no problem.

**Comment by TamaBaka** [comment]
If it does work, try this modification...
From 
**if not header.startswith('\xde\xad\xbe\xef\x04'):**

to
**if header[:4] != b'\xde\xad\xbe\xef\x04':**

**Comment by TamaBaka** [comment]
Or Plan B, delete the following 3 lines:

```
    if not header.startswith('\xde\xad\xbe\xef\x04'):
        print args[0] + " doesn't appear to be TeslaCrypted"
        return
```

We lose the sanity check, but we get directly to the data processing.

**Comment by fedeq4** [comment]
plan A didnt work.. 

plan B DID! instantly..? 

![sin titulo](https://cloud.githubusercontent.com/assets/16376212/11929746/59f671de-a7bc-11e5-8637-f0c434cdc1a2.jpg)

**Comment by TamaBaka** [comment]
Okay, Plan B has given you a candidate key to try.  Go to step 7.

Ah, but I suggest piping the output to a file so that you can copy and paste instead of manually typing out the candidate key.

Add something like this to the array:
'9AB187758A71417382CD7A5717B9C99D42091C2B6FD9F68FDFC1266B75458142B6EB3E331145B7F4C3C712500F8125EBF290981EE2E88CA009B1588D22B2CA69': b'\xE9\xF3...

**Comment by fedeq4** [comment]
so in known keys i shuld put ´hex key´ : b'...´.?

how can i pipe the key to a .txt?

**Comment by TamaBaka** [comment]
Yes.  
**'public key': candidate key**
where public key is that Hex that you found at the very beginning and candidate key is that b'x...' that you're given by unfactor.

As for piping the output...

**python unfactor.py mb_cpu.jpg.vvv 5 11 19 23 29 47 1181 3457 352483 1619691517 74143191606114801079972109 231419295217707765832329200835295551851 6183853869962559015040993794542699128471266939221704979810413 > output.txt**

Open up output.txt

**Comment by fedeq4** [comment]
Im about to cry... it worked!!! 

it shuld be the same key for every file?

**Comment by TamaBaka** [comment]
I believe that the key would be different if you were hit by the ransomware multiple times and you never bothered to decrypt the previous attempts.  

Once decryption is finished, instead of deleting them, I'd keep the vvv files in a separate directory just in case a file didn't decrypt properly.  You can go back to it and try again.

**Comment by fedeq4** [comment]
i dont know what to say @TamaBaka ..... YOU and all the people that help me, directly or indirectly ROCKS!! 
I dont know how to repay you...

**Comment by TamaBaka** [comment]
No need.  I was doing community service because I couldn't find a way to thank Googulator.

Are your decrypted files opening properly?

**Comment by fedeq4** [comment]
the couple that i tried yes, perfectly.. how would be the parameter on cmd to decrypt a particular folder? when i put "tesla crack.py C:\Users\Fede\Desktop\some folder" it says cannot acces? do i have to do it manualy? at this point isn´t even a problem.. but it whuld be nice so i can do it folder by folder just to be sure that nothing is left behind.

more that community service, you and googulator are SAIVIORS!

im so glad that even though i dont have the money to pay up to the hackers, with people like googulator and you, isn't nessesary, and maybe more and more people can work arround this and make the ransomwares obsolete

**Comment by TamaBaka** [comment]
That's a permission problem.   

If possible, you can try starting windows explorer using admin privilege and attempt to open the folder.  You'd probably need to run teslacrack with admin privileges too.

If that doesn't work, you can either go to the folder and set permissions so that you can access it, or log in to a user that can open that folder.

**Comment by Googulator** [comment]
Fixed in revision b2c0e6da3fc586c4b721b47bff9b279645f6ffcf, now both 0xdeadbeef and 0x00000000 are treated as valid TeslaCrypt magic numbers.

BTW, to factor with YAFU, you must first convert the key to decimal, then use factor(decimal). Fortunately, converting a large number from hex to decimal is easy using Python:

```
C:\> python
>>> 0x<long hex number>
<decimal representation of long hex number>L
>>> exit()
```

Then, just remove the final L added by Python, and you're good to go.

Also, on a multi-core machine, run yafu with the "-threads X" option, where X is the number of threads to use. Recommended: X = (number of cores) \* (number of HyperThreads per core, typically 2 for normal HyperThreaded CPUs)  - 1. This leaves one core/thread free for other tasks, so you can continue to use your computer while factoring - if you want to dedicate your computer entirely to factoring, and gain some more speed, omit the -1.

**Comment by joseluu** [comment]
Yafu finds the factors extremely fast (in minutes), here is the syntax of
an example (all on one line):

yafu-x64.exe
"factor(0x0F865F66648521289CB231333DD1F08BFB8DF8BC2605C7334B3002F135C1E81065BBC0A78E3E1005AE5E276416E038ACD9F828514AD80ABDFC06493E7A5C5680)"
-threads 8

**Comment by artoes** [comment]
Found mine too in about 20 minutes with yafu, it was incredibly fast!
I think it is interesting to give it a try before going for the long 
run!(msieve)

Thanks again Googulator, very very nice work :)

------ Message d'origine ------
De : "Godziluu" notifications@github.com
À : "Googulator/TeslaCrack" TeslaCrack@noreply.github.com
Cc: "artoes" leo.geoffroy@laposte.net
Envoyé 21/12/2015 23:04:35
Objet : Re: [TeslaCrack] Magic numbers to 0s (#3)

> Yafu finds the factors extremely fast (in minutes), here is the syntax 
> of
> an example (all on one line):
> 
> yafu-x64.exe
> "factor(0x0F865F66648521289CB231333DD1F08BFB8DF8BC2605C7334B3002F135C1E81065BBC0A78E3E1005AE5E276416E038ACD9F828514AD80ABDFC06493E7A5C5680)"
> -threads 8
> 
> On Mon, Dec 21, 2015 at 8:35 AM, Martin Manuel Valdez Bello <

**Comment by joseluu** [comment]
I was not able to recover fhe private key using the unfactor.py, it stays
either silent (no output) or spits many times the same short key.

Have you had any success with the later steps ?

**Comment by artoes** [comment]
Yeah everything works, currently decrypting my files
I just saw back your mail, I think yafu only accepts integers as stated 
by Googulator, so you should use :
factor(813104632805074587096483805541334022781032209379994339527363946039493079321473232167342066990114458580278049248137525255862552562115544020211835076368000)

Just run the script, I found:
P1 = 2
P1 = 2
P1 = 2
P1 = 2
P1 = 2
P1 = 2
P1 = 2
P1 = 3
P1 = 5
P1 = 5
P1 = 5
P2 = 13
P2 = 13
P2 = 13
P8 = 41009147
P19 = 3969410779247198567
P23 = 52996804489235183176277
P23 = 12184931593559771488159
P74 = 
73349233722096492705822838995107772228051422889559226244224893115452014929

Confirm if you got the same result

------ Message d'origine ------
De : "Godziluu" notifications@github.com
À : "Googulator/TeslaCrack" TeslaCrack@noreply.github.com
Cc: "artoes" leo.geoffroy@laposte.net
Envoyé 22/12/2015 00:21:08
Objet : Re: [TeslaCrack] Magic numbers to 0s (#3)

> I was not able to recover fhe private key using the unfactor.py, it 
> stays
> either silent (no output) or spits many times the same short key.
> 
> Have you had any success with the later steps ?

**Comment by joseluu** [comment]
Yes,  got the same factors.

I had misread step 6. I got correct decoding now. Thanks to all...   no
ransom to pay.

**Comment by flazh99** [comment]
Hey i did all the steps.
My Hex Sting is: E836ECC94557FB79A6E71D7AEA4867D688686C06503E854F6B6AEAC0CAA1B9577A6DCE5A7C1E28E5329A03E09C9353BD2BC2FEA9F1F100C7DA19DF79D972969F

Factors using yafu: 
P1 = 3
P1 = 3
P1 = 3
P1 = 3
P2 = 83
P3 = 271
P3 = 389
P5 = 51869
P6 = 114769
P8 = 28912607
P13 = 2766537563071
P12 = 179756071823
P18 = 567412261382607197
P30 = 917344692257464338723186217847
P57 = 385171465067318664775134453175017986681644161058243731631

ans = 1

Candidate AES private key: b'\xed\x9f\x71\x43\xf1\x77\xe2\x83\x07\x96\x90\xeb\xc
5\x34\x69\x6c\xe7\x3a\x33\x78\x31\x89\xe1\xdc\xe6\xf8\x79\x9a\x66\x41\x5b\x3f' (
ED9F7143F177E283079690EBC534696CE73A33783189E1DCE6F8799A66415B3F)

But i still cant decrypt my files. Did I something wrong?
I found the Hex-string using a Hex editor on an encryptet jpg. I chose the second one. May someone could help me to solve the problem. Teslacrack.py says: cannot access... when i try to decrypt
