### ISSUE TITLE
Can .micro files be decrypted?

### ISSUE THREAD

**Issue by nickborromeo** [Googulator/TeslaCrack#30]
I am not sure by this change to the read me. Can you elaborate? Does this mean that decrypting `.micro` files is being worked on? 

https://github.com/Googulator/TeslaCrack/commit/cc1f98b9c33bd71de3d9bbfbc86612e133d28072#diff-88b99bb28683bd5b7e3a204826ead112R131

Thank you for all the work you are doing.

cc @ankostis

**Comment by Demonslay335** [comment]
No, TeslaCrypt 3.0 cannot be cracked currently. The commit is simply acknowledging the existence of the new (uncrackable) extensions. If a solution is found, it will be a completely different tool, as the newest variants are not weak to the same factorization attack.

**Comment by Demonslay335** [comment]
@nickborromeo 

Just wanted to make sure you got the news that all versions of TeslaCrypt are now decryptable. :)

http://www.bleepingcomputer.com/news/security/teslacrypt-shuts-down-and-releases-master-decryption-key/
