### ISSUE TITLE
Factor too large

### ISSUE THREAD

**Issue by hermanndp** [Googulator/TeslaCrack#31]
Hi all,
when I execute python unfactor.py xxxxxxxxxxx.pdf.ccc 2 2 5 5 5 5 5 7 7 13 13 79 179 727 23287031 87997795387 126387631454068390647405875848961 94351176187478743311192960811949754038003461377288092311347994551569248390026437807239
I encounter the following error
Factor too large: 94351176187478743311192960811949754038003461377288092311347994551569248390026437807239

My decimal key is "2600429819775846731396113914037945376810164361866204905740413453239417501452042023158000725351646872397443751459858788275784561373667322125619112962753125"
I already factorized it and uploaded on factordb.com to make it available to the public.

Editing the script to allow more digits, I had error of my previous post: factors don't divide the AES Key.

Am I wwong with something?
Thanks in advance
Hermann

**Comment by Demonslay335** [comment]
You must have a copy/paste error when you started factoring, as you have not uploaded any factors to the decimal number you posted. I have just now posted the factors for you.

http://www.factordb.com/index.php?id=1100000000820953132

**Comment by hermanndp** [comment]
Thanks, I just saw the mistake...
Infact an odd number can't be divided by 2!!!

**Comment by ankostis** [comment]
You don't need to paste each prime-factor multiple times - once is enough.
