### ISSUE TITLE
Cannot open TeslaCrack-master.zip. Windows says file is invalid

### ISSUE THREAD

**Issue by RWM2500** [Googulator/TeslaCrack#36]
Cannot open TeslaCrack-master.zip. Windows says file is invalid

**Comment by Demonslay335** [comment]
Interesting. I use 7zip, so I wasn't able to reproduce until I forced Explorer to open it. Could be GitHub's build process. I'm seeing some other people complaining on other projects, and some resolved by messing with bower, which I don't believe this project uses.

**Comment by RWM2500** [comment]
Tried on two computers. Downloaded 7Zip and all is well.
Thanks for the tip. Don't know why I didn't try that sooner.
