### ISSUE TITLE
Help decrypting a file

### ISSUE THREAD

**Issue by Totalis** [Googulator/TeslaCrack#37]
I have tried to decrypt a couple of ransomed files and I have been given the AES and the BTC keys.  I have then converted them using python and then found the factors on factorDB.  I am then trying to use the unfactor script but it reports one of the factors as too large.

`D:\>python teslacrack.py -v DSCF6416.JPG.vvv
2016-03-23 18:42:42,188:DEB: Options: Namespace(delete=False, delete_old=False,
dry_run=False, fix=False, fpaths=['DSCF6416.JPG.vvv'], overwrite=False, progress
=False, verbose=True)
2016-03-23 18:42:42,188:WAR: Unknown key: b'01F79E3E9230D8FE52E8C6F4E54A535E022D
25057BDF59D18D9B20A2FF14A1DF61566C9C584886D3C86C07687045B3B64FF0C7B4B21AB8AB30C9
0850A5D76A0C'
  in file: \\?\D:\DSCF6416.JPG.vvv
2016-03-23 18:42:42,188:INF: +++Unknown key(s) encountered: 1
     AES: '01F79E3E9230D8FE52E8C6F4E54A535E022D25057BDF59D18D9B20A2FF14A1DF61566C9C584886D3C86C07687045B3B64FF0C7B4B21AB8AB30C90850A5D76A0C'
     BTC: '7FEC141167E9A33B11BA1045170F7CE3888877CB56A2C097D6ADB186AF233DB0FDB11D4D93F74019D596DA1C19CA6E25B9A5A509651142B6FC9F3CE846D48F5E'
    File: '\\\\?\\D:\\DSCF6416.JPG.vvv'
  Use`msieve`on AES-key(s), or`msieve`+`TeslaDecoder` on Bitcoin-key(s) to
crack them!
2016-03-23 18:42:42,188:INF: +++Dir     0
       scanned:       0
  noAccessDirs:       0
      teslaExt:      1
       badheader:      0
         crypted:      1
         decrypted:      0
           skipped:      0
           unknown:      1
            failed:      0

```
   overwritten:      0
   badExisting:      0
       deleted:      0
```

`

The python command (and the resulting number is:
`int('01F79E3E9230D8FE52E8C6F4E54A535E022D25057BDF59D18D9B20A2FF14A1DF61566C9C584886D3C86C07687045B3B64FF0C7B4B21AB8AB30C90850A5D76A0C', 16)
103033681052207294038955016635698361218065744565489366163984656363176252081804167360825676976119585314573995927388151222246805717310008618881907525380620`

That number is on factorDB but it contains a factor which is too large.  

What am I doing wrong?  Thanks for the amazing utility btw :D

test file
https://dl.dropboxusercontent.com/u/5224931/DSCF6416.JPG.vvv

Thanks
 Greg

**Comment by ankostis** [comment]
The [last factor of your key](http://factordb.com/index.php?id=1100000000829448494) has 121 digits and it is "composite", so it can be further factorized.
You have to try the `msieve` or similar external programs, as suggested by the command line and the README.
