### ISSUE TITLE
Unfactor.py does not appear to properly identify teslacrypted files

### ISSUE THREAD

**Issue by TamaBaka** [Googulator/TeslaCrack#4]
A previous issue was hijacked for troubleshooting. During which, while running through each step, we hit a roadblock while attempting to run unfactor.py.

Until we removed the check completely, we continued to get a "the file doesn't appear to be teslacrypted." error.  

I'm not too familiar with python so I'm not sure why the comparison check failed.  It looks like a type conversion problem though.

**Comment by Googulator** [comment]
This is a new version of TeslaCrypt, which uses 0x00000000 instead of 0xdeadbeef as its file magic. Assuming the encryptiuon scheme is unchanged, I will add support for it soon.

**Comment by Googulator** [comment]
Please verify whether the latest revision fixes this.

**Comment by Googulator** [comment]
I was able to decrypt the sample file in the other issue with the updated TeslaCrack, and no reply here, closing.

**Comment by TamaBaka** [comment]
Sorry, I didn't have a valid file to test it on.  I wanted to test it on a JPG file but I only have pdf's as samples.  I was hoping that an incoming job would provide the necessary sample but I just found out that it was attacked by a different ransomware.
