### ISSUE TITLE
Unlucky key?

### ISSUE THREAD

**Issue by cvelde** [Googulator/TeslaCrack#8]
Hey,
I'm just wondering about the following key:

Software has encountered the following unknown AES keys, please crack them first using msieve:
30E8B530B85EAA121593461B55D8ABE7C6FA8FA53932BA873EE2F2C0BA77C16A4409214F16202EDC155941C3327B8FD414940AD8C57D6C5E6F1FAC73EC06B92B found in ./1.pdf.vvv

Had my Computer working on it for a about a week now, running both yafu(x64) and factmsieve on different cores (1 Core each) now results on the C146 yet.

Is the key just really hard (how do I determine that?) or is my Phenom II x4 640 just really bad for this kind of calculation? (I know its no i7, but still should be okay?!)

Many thanks in advance

**Comment by Googulator** [comment]
Really unlucky key, if you have a C146 left over after ECM. Try the Bitcoin key.

**Comment by cvelde** [comment]
This is the Bitcoin key: 0CC63F53085BCB9857D24488230442BDF88E114258F7353D14ED51DD2E2EEC5549CCB275963E3F41F05A5A19CA3A62B9B9B9A94FDF5DC74E9064D37AB120AEAF 

Also has a C120, still running, so it's the key - not my cpu? I wonder how long it will take, anybody got an idea?

**Comment by Googulator** [comment]
Should take about a day or two. Use factmsieve.py for a C120.

Edit: Factor on all cores. It makes a big difference.

**Comment by darkskysofrenia** [comment]
really unlucky .... i've got another 154 integer digt key ( 153 for bitcoin key ... ) for a friend :

0x0BD5B4F3CB4D761648C9BD9AA4A03E570D14294E8499A5F9F05D7574278A1D5A79D5A19D1BEB34B196D0040B9E25EB253C9EB45FDAC4EFB6AFB9C10EEBFE8FD2

and 0x011D0EFB624CEFD37512A80E3D62246CFBECAF625A66B9E758C2A810BB2F84E707D8DF59AE62AD1560BCF7AE12CE490F437ABAF4BE7963CD7647C23F42B83B84

is someone can explain me why my dual Xeon ( 12cores/24threads@ 3.06Ghz ) still working on it scince 3 days ... with msieve.py (on all threads ) ... the same computer factorize one other teslacrypt key ( 0xA1B1F4E0D4D3F9411844494419B353628E6C69AE1129FF301DE74B4559E4212491AEBBA9BF2721D64B8D0157A415FEB2386C9D2E2D071D22C3441B1D95E48CBB )
in only 58 seconds ...

**Comment by Googulator** [comment]
Hi,

Did msieve perform a successful ECM step? Some versions of it floating around the Net don't have ECM built in (since msieve is mostly used for cracking RSA, and ECM is useless there), and will take very long even for easy keys.

Also, are you seeing consistently high CPU usage on all cores? A system like yours should be able to fully factorize even RSA-155 in 3 days.

**Comment by darkskysofrenia** [comment]
the first msieve ( launched by exe of msieve ) failed http://pastebin.com/9G7b2s0m byt the second one launched by msieve.py still runing approximatively scince thursday 31.12.2015 20h00. i ve try a lot of solution including wolfarm && factor db trying to only factor composite and add already know factor but unfactor.py give no output.. i've put somme print in code to see if he goes inside loops , the print out but no error check your factor or  key possible ...

**Comment by Googulator** [comment]
That's a C106 after removing easy factors.

How many relations has it collected?

**Comment by darkskysofrenia** [comment]
i don't know , i'm not familiar with factorisation, it's running in "verbose mode" it's actualy output lines like this http://hpics.li/df8c40e

**Comment by Googulator** [comment]
That's polynomial selection. And your factmsieve.py is old. Use the one from factmsieve.86.zip
(Let polynomial selection complete, then switch over to the newer version once it begins sieving.)

**Comment by darkskysofrenia** [comment]
where can i found last version ( compiled for windows <- sorry no one is perfect... my wife need it for 3d rendering applications ) or can i use cuda computation software on my old dual xeon ( dual 5140 8Go but  LinuxMint and Geforce GTX670 4Go 1344Cuda cores ) ? and how to safely switch version for terminate factorisation ?

**Comment by Googulator** [comment]
factmsieve.py doesn't need to be compiled, it's just a Python script which runs the same on all platforms.

Google for factmsieve.86.zip.

Your msieve.exe appears to be fine, only the Python wrapper is old.

**Comment by darkskysofrenia** [comment]
Thks again, i continue to try , hope found factors soon

**Comment by Demonslay335** [comment]
@cvelde 

If you haven't finished factoring, your factors are on [factordb.com](http://www.factordb.com/index.php?query=669049812256450395854861982155854994670827546845933836493631391450944178267792261571810604377488347814935453322192794059211194705945450773625944949173935).

@darkskysofrenia 

If you haven't finished factoring, your first key's factors are on [factordb.com](http://www.factordb.com/index.php?query=619838370694573489677615657761314429981701046554484927594725478425232273862780267750658149602941057652096353317803469670070211348863163671132406890270674)

**Comment by Googulator** [comment]
Closing dead support ticket.
